In [ ]:
## Inspecting an array
There are two methods to inspect an array

In [ ]:
import numpy as np

# Create 3 arrays with different shapes
a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])
c = np.array([[(1,2,3,4),(5,6,7,8)], [(9,10,11,12),(13,14,15,16)]])

#shape returns the number of elements in each dimension
print(a.shape)

print(b.shape)

print(c.shape)


### Using len, ndim, size
```len``` gives the number of elements in the first dimension of an array, but does not count how you might think!<br> 
```ndim``` counts the number of dimensions in one array<br>
```size``` counts the total TOTAL number of elements inside your specified array<br>

In [ ]:
import numpy as np
# Create 3 arrays with different shapes and sizes
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3),(4,5,6)])
c = np.array([[(1,2,3,4),(5,6,7,8)], 
              [(9,10,11,12),(13,14,15,16)],
             [(17,18,19,20),(21,22,23,24)]])

# Size of the first dimension 
print('====len====')
print(len(a));print(len(b));print(len(c))
print(a)
print(b) #(1,2,3) is one element, (4,5,6) is the second
print(c) #[1..8], [9...16], [17...24] are three "elements"
# Number of dimensions
print('====ndim====')
print(a.ndim);print(b.ndim);print(c.ndim)

# Total number of elements across dimensions
print('====size====')
print(a.size);print(b.size); print(c.size)


## Manipulating Arrays
There are many functions to manipulate arrays. Here's the cheatsheet:
### Change Array Shape
 ```Flatten()```
 ```reshape()```
### Transpose Array
```transpose()```
### Combine Arrays
```concatenate()```
### Add/Remove Elements
```append()```
```insert()```
```delete()```

### Changing Array Shape
#### ```Flatten()```
Penyet ur multidimensional array into a one-dimensional one.

In [ ]:
import numpy as np

b = np.arange(24).reshape(2,3,4) # b= [[[0,1,2,3],[4,5,6,7],[8..],[20,21,22,23]]]

c = b.flatten()

print(b,"\n=====") 
print(c) #[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

c[0] = 100;  # change the first value in the copy
print(b) 
print(c) #[ 100  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

#### Changing Array shape with ```reshape()```
Modifies the shape of an array, without changing the original array, or modifying any of its data.

In [ ]:
import numpy

my_fruits = numpy.array(["apple","banana","cherry","durian","elderberry","Figs"])
print(my_fruits)
print()
print(numpy.reshape(my_fruits,(3,2)))


#### Changing Array shape with ```shape()```
Return shape of an array

In [ ]:
import numpy as np

a= np.array([1, 2, 3, 4, 5])
print(a.shape)     #(5,) -> 5 rows and 0 columns

b = np.array([[1, 2],[3, 4],[6,5]])
print(b.shape) #(3, 2) -> 3 rows and 2 columns 

#### Changing Array shape with ```resize()```
Like reshape, but will add/discard data

In [ ]:
import numpy as np

a=np.array([[0,1],[2,3]]) #2x2

print(f"resize array a to 4x1: \n{np.resize(a,(4,1))}\n===") # not allowed in reshape

print(f"resize array a to 2x3: \n{np.resize(a,(2,3))}\n===") # not allowed in reshape

b = np.array([(1,2),(3,4),(5,5)])
print(b)
print(np.ndim(b))

#### Changing Array shape with ```transpose()```
Modifies the shape of an array, without changing the original array, or modifying any of its data.

### Combining arrays 
#### Changing Array shape with ```concatenate()```
Two or more arrays can be concatenated using concatenate() function along an axis  
The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default). <br>
- axis = 1 will concatenate on the  "y axis", axis 0 will concatenate on the x axis <br>

Syntax: ```numpy.concatenate((a1, a2, ...), axis=0)```


In [ ]:
# Concatenating a 1 dimensional array
import numpy as np

# 1-D array
x = np.arange(5)
y = np.arange(6,10)
z = np.arange(11,15)

print(x);print(y); print(z)
print(np.concatenate((x,y,z)))


In [ ]:
# Concatenating a 2 dimensional array

import numpy as np

# 2-D array
a = np.array([(1,2),(5,6)])
b = np.array([(1,3),(4,7)])
print(a)
print("*"*5)
print(b)
print("*"*10)

c = np.concatenate((a,b))
print(f"array a is: \n{a}");print(f"array b is: \n {b}");
print("*"*10)

#print(np.concatenate((a,b)))
print(f"By default, axis is on 0: \n{np.concatenate((a,b), axis=0)}")
print("*"*10)
print(f"axis on 1: \n{np.concatenate((a,b), axis=1)}")


In [ ]:
### tryna figure out axis
import numpy as np

## kinda like adding two different matrices together

# 2-D array
a = np.array([(1,2,3,4),(7,8,9,10)])
b = np.array([(5,6),(4,7)])

print(f"axis on 1: \n{np.concatenate((a,b), axis=1)}")


### Adding/Removing elements
#### Adding values to the end of an array with ```Append()```
Syntax: ```numpy.append(arr, values, axis=None)``` <br>
Values must be of the correct shape<br>
If axis is not specified, values can be any shape and will be flattened before use! <br>

In [23]:
import numpy as np

x = np.array([(1,2,3), (4,5,6)])
print(x);print()

# no axis specified
appendedx = np.append(x, np.array([7,8]))
print(appendedx);print()
appendedx = np.append(x, np.array([7,8,9]))
print(appendedx);print()

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6 7 8]

[1 2 3 4 5 6 7 8 9]



In [29]:
import numpy as np

x = np.array([(1,2,3), (4,5,6)])
print(x);print()

# axis specified
x1 = np.append(x, np.array([(7,8,9)]),axis = 0)
x2 = np.append(x, np.array([(7,8), (9,10)]),axis = 1)
#x2 = np.append(x, np.array([(7,8), (9)]),axis = 1) 
# code will end in error, as the array is strict about its dimensions

print(x1);print()
print(x2);print()

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]



#### Inserting values with ```insert()```
This isn't inside the notes, but I figured i'd just reiterate.<br>
```insert()``` allows you to insert values at the specified indices<br>
Syntax: ```numpy.insert(arr, obj, values, axis=None)```<br>
Where ```arr``` is the array you wanna insert into, ```obj``` is the defined index, and ```values``` is the values you wanna insert.

In [34]:
import numpy as np
insertEg = np.array([[1, 1], [2, 2], [3, 3]])
print(insertEg),print("*"*20)
#       .insert(arr     , obj, values, axis=None)
print(np.insert(insertEg, 0, [7,8,9])),print("*"*20)
print(np.insert(insertEg, 2, [7,8,9])),print("*"*20)


print(np.insert(insertEg, 1, [5,6,7], axis=1)),print("*"*20)



[[1 1]
 [2 2]
 [3 3]]
********************
[7 8 9 1 1 2 2 3 3]
********************
[1 1 7 8 9 2 2 3 3]
********************
[[1 5 1]
 [2 6 2]
 [3 7 3]]
********************


(None, None)

In [2]:
import numpy as np
x = np.arange(8).reshape(2, 4)
print(x)
idx = (1, 3)
np.insert(x, idx, 999, axis=1)


[[0 1 2 3]
 [4 5 6 7]]


array([[  0, 999,   1,   2, 999,   3],
       [  4, 999,   5,   6, 999,   7]])