## Splitting Arrays
Three common functions to split arrays in numpy are: ```split()```, ```hsplit()```, ```vsplit()```. Let's start with the simplest!

### ```split()```
Split an array into multiple sub-arrays<br>
Syntax: ```numpy.split(array, indices_or_sections, axis=0)```


In [ ]:
import numpy as np

x = np.arange(9.0)
y = np.split(x, 3)

print(x)
print(y)

### ```hsplit()```
Split an array into multiple sub-arrays horizontally (column-wise) <br>
Equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension<br>
Syntax: ```numpy.hsplit(array, indices_or_sections)```

In [ ]:
a = np.arange(12).reshape(3,4)

b = np.hsplit(a,2)
c = np.hsplit(a,4)

print(a)
print(b)
print(c)
#Observe the way it iterates

### ```vsplit()```
Split an array into multiple sub-arrays vertically (row-wise)<br>
equivalent to split with axis=0 (default), the array is always split along the first axis regardless of the array dimension<br>
Syntax: ```numpy.vsplit(array, indices_or_sections)```

In [ ]:
import numpy as np

x = np.arange(12.0).reshape(4, 3)
y = np.vsplit(x, 2)

print(x)
print(y)

### Copying and Sorting Arrays
```copy()``` and ```sort()``` are very powerful, but need some time to understand

In [ ]:
import numpy as np

# Create 2 arrays with different data types, shapes and sizes
a = np.array([10,2,8,4,6,1,5,9,3,7])

sortednumbers = np.copy(a)
sortednumbers.sort()

print(a)
print(sortednumbers)

#### More examples with sort()
```sort()``` sorts according to the ASCII Table! So generally its: !?@special chars -> UPPERCase -> lower case

In [ ]:
import numpy as np

# Create 2 arrays with different data types, shapes and sizes
insects = np.array([("aphid","Cricket","mosquito"),("bee","cricket","fruit fly")])
print(insects),print()

sortOn0 = np.sort(insects, axis = 0) #sort vertically/along columns
print(sortOn0)
sortOn1 = np.sort(insects, axis = 1) #sort horizontally/along the rows
print(sortOn1)

### Subsetting, Slicing, Indexing
Subsetting is retrieving specific parts of a large file.<br> 
In the numpy context, we select a specific number of elements in an array.<br>
You're likely already familiar with the concept, if you've interacted with an array in python!

In [ ]:
import numpy as np

a = np.arange(9) # a = [0,1,2,3,4,5,6,7,8]

# Select the element at index 2
print(a[2])

# Select elements from index 0 to 7 with step 2
print(a[:7:2])

# Select and reverse elements from index 0 to the end
print(a[::-1])

In [ ]:
# subsetting and slicing in 1-D
import numpy as np
insectArray = np.array(["aphid","Cricket","mosquito"])
print(insectArray),print()

print(insectArray[0]) # selects the first element in the first row 
print(insectArray[0][1]) #selects the second character, from the first row (recall how strings are stored as lists)


In [ ]:
# subsetting and slicing in 2-D
import numpy as np
insectArray = np.array([("aphid","Cricket","mosquito"),("bee","cricket","fruit fly")])
print(insectArray),print()

print(insectArray[0]) # select the first row (recall that python counts from zero)
print(insectArray[0][1]) # selects the second element in the first row 
print(insectArray[0][1][2]) # selects the third character, from the blablabla (recall how strings are stored as lists)

print("====")
print(insectArray),print()

print(insectArray[1,2])
print(insectArray[1,-1]) #Last element in second row
print(insectArray[-1,2])
print(insectArray[-2,2]) #Second last row, second element
print(insectArray[1,0:2])
print("=====")
print(insectArray[0:2,0:2])
print(insectArray[0:5,2])

#### Slicing in even more dimensions


In [ ]:
import numpy as np

# Create an array with 0 to 23 and reshape it into a 2x3x4 array # Think of it as an Excel workbook with 2 worksheets
# Each worksheet has 3 rows,4 columns
b = np.arange(24).reshape(2,3,4)
print("Column b is:\n", b),print()

# Select worksheet 2, Row 2, Col 4
print("Select worksheet 2, Row 2, Col 4:\n", b[1,1,3])  # 19

# Select both worksheets, Row 1, Col 1
print("Select both worksheets, Row 1, Col 1\n", b[:,0,0])  # 0 12

# Select first worksheet, all rows and columns
print("Three ways of selecting the entire array in the 1st dimension")
# Method 1
print(b[0]) 
# Method 2
print(b[0, :, :])
# Method 3, Ellipsis replaces the multiple colons
print(b[0, ...])


In [25]:
# Slicing a string array
import numpy as np

insectArray = np.array([[("aphid","grasshopper","mosquito"),("bee","cricket","fruit fly")],[("Tarantula", "Black Widows", "Brown Spider"),("Buzzing Bees","Honey Bees","Exceptionally good Bees")]])
print(insectArray),
print("dimensions of the insectArray are", insectArray.shape) 
print("*"*20)

print(insectArray[1,1,2])
print("Skipping every other element:", insectArray[1,1,::2])
print("Selecting the first two elements of every dimension: ", insectArray[:,0,0:2])

[[['aphid' 'grasshopper' 'mosquito']
  ['bee' 'cricket' 'fruit fly']]

 [['Tarantula' 'Black Widows' 'Brown Spider']
  ['Buzzing Bees' 'Honey Bees' 'Exceptionally good Bees']]]
dimensions of the insectArray are (2, 2, 3)
********************
Exceptionally good Bees
Skipping every other element: ['Buzzing Bees' 'Exceptionally good Bees']
Selecting the first two elements of every dimension:  [['aphid' 'grasshopper']
 ['Tarantula' 'Black Widows']]


## Indexing
Boolean indexing lets you indicate if an element should be included<br>
In the example below, we want to create an array with only the even numbers<br>

In [34]:
import numpy as np

a = np.random.randint(20, size=12).reshape(2,6)
print(a)

b = a % 2 == 0
print(b)

a = a[b]

print(a)

[[ 7 16  9 18 12 11]
 [18  9  8 12  5  1]]
[[False  True False  True  True False]
 [ True False  True  True False False]]
[16 18 12 18  8 12]


#### Addl Example
Additional operations!

In [43]:
import numpy as np

a = np.random.randint(12, size=12).reshape(4,3)
print(a)

divisibleBy3 = a % 3 == 0
print(divisibleBy3)
print("Numbers divisible by 3:", a[divisibleBy3])
print("="*20)
oddNumberIndex = a % 2 == 1
print(oddNumberIndex)
print("Odd numbers:", a[oddNumberIndex])

[[11  8  9]
 [ 8 10  8]
 [ 8  2  3]
 [ 1  3  5]]
[[False False  True]
 [False False False]
 [False False  True]
 [False  True False]]
Numbers divisible by 3: [9 3 3]
[[ True False  True]
 [False False False]
 [False False  True]
 [ True  True  True]]
Odd numbers: [11  9  3  1  3  5]
